// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: grpc/grpc.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Grpc {
  public static partial class grpc
  {
    static readonly string __ServiceName = "grpc.grpc";

    static readonly grpc::Marshaller<global::Grpc.HelloRequest> __Marshaller_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Grpc.HelloResponse> __Marshaller_HelloResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.HelloResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Grpc.HelloRequest, global::Grpc.HelloResponse> __Method_SayHello = new grpc::Method<global::Grpc.HelloRequest, global::Grpc.HelloResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_HelloRequest,
        __Marshaller_HelloResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Grpc.GrpcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of grpc</summary>
    public abstract partial class grpcBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Grpc.HelloResponse> SayHello(global::Grpc.HelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }
    }

    /// <summary>Client for grpc</summary>
    public partial class grpcClient : grpc::ClientBase<grpcClient>
    {
      /// <summary>Creates a new client for grpc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public grpcClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for grpc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public grpcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected grpcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected grpcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Grpc.HelloResponse SayHello(global::Grpc.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Grpc.HelloResponse SayHello(global::Grpc.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Grpc.HelloResponse> SayHelloAsync(global::Grpc.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Grpc.HelloResponse> SayHelloAsync(global::Grpc.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override grpcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new grpcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(grpcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello).Build();
    }

  }
}
#endregion
