genny -imp "github.com/golang/protobuf/proto" -in .\generic.go.1 -out Header.pb.go gen "T=Header"
genny -imp "github.com/golang/protobuf/proto" -in .\generic.go.1 -out Content.pb.go gen "T=Content"
genny -imp "github.com/golang/protobuf/proto" -in .\generic.go.1 -out LoginMessage.pb.go gen "T=LoginMessage"
genny -imp "github.com/golang/protobuf/proto" -in .\generic.go.1 -out LogoutMessage.pb.go gen "T=LogoutMessage"
genny -imp "github.com/golang/protobuf/proto" -in .\generic.go.1 -out Command.pb.go gen "T=Command"
genny -imp "github.com/golang/protobuf/proto" -in .\generic.go.1 -out CommandResult.pb.go gen "T=CommandResult"
genny -imp "github.com/golang/protobuf/proto" -in .\generic.go.1 -out ClientListResut.pb.go gen "T=ClientListResut"
genny -imp "github.com/golang/protobuf/proto" -in .\generic.go.1 -out MessageHistories.pb.go gen "T=MessageHistories"
protoc --go_out=.\ .\message.proto