// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package proto

import p "github.com/golang/protobuf/proto"

func ProtoMarshal(t LogoutMessage) ([]byte, error) {
	return p.Marshal(&t)
}

func ProtoUnmarshal(bytes []byte) (t LogoutMessage) {
	p.Unmarshal(bytes, &t)
	return t
}
