// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Header
	Content
	LoginMessage
	LogoutMessage
	Command
	CommandResult
	ClientListResut
	MessageHistories
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Type   int64 `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	Length int64 `protobuf:"varint,2,opt,name=Length" json:"Length,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto1.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Header) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

// 消息体
type Content struct {
	Head      *Header `protobuf:"bytes,1,opt,name=Head" json:"Head,omitempty"`
	Content   string  `protobuf:"bytes,2,opt,name=Content" json:"Content,omitempty"`
	Publisher string  `protobuf:"bytes,3,opt,name=Publisher" json:"Publisher,omitempty"`
	Time      int64   `protobuf:"varint,4,opt,name=Time" json:"Time,omitempty"`
}

func (m *Content) Reset()                    { *m = Content{} }
func (m *Content) String() string            { return proto1.CompactTextString(m) }
func (*Content) ProtoMessage()               {}
func (*Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Content) GetHead() *Header {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Content) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Content) GetPublisher() string {
	if m != nil {
		return m.Publisher
	}
	return ""
}

func (m *Content) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// 登入消息
type LoginMessage struct {
	Head *Header `protobuf:"bytes,1,opt,name=Head" json:"Head,omitempty"`
	Name string  `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Id   int32   `protobuf:"varint,3,opt,name=Id" json:"Id,omitempty"`
}

func (m *LoginMessage) Reset()                    { *m = LoginMessage{} }
func (m *LoginMessage) String() string            { return proto1.CompactTextString(m) }
func (*LoginMessage) ProtoMessage()               {}
func (*LoginMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginMessage) GetHead() *Header {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *LoginMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 登出消息
type LogoutMessage struct {
	Head *Header `protobuf:"bytes,1,opt,name=Head" json:"Head,omitempty"`
	Name string  `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Id   int32   `protobuf:"varint,3,opt,name=Id" json:"Id,omitempty"`
}

func (m *LogoutMessage) Reset()                    { *m = LogoutMessage{} }
func (m *LogoutMessage) String() string            { return proto1.CompactTextString(m) }
func (*LogoutMessage) ProtoMessage()               {}
func (*LogoutMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LogoutMessage) GetHead() *Header {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *LogoutMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogoutMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 操作信息
type Command struct {
	Head          *Header `protobuf:"bytes,1,opt,name=Head" json:"Head,omitempty"`
	OperationType int64   `protobuf:"varint,2,opt,name=OperationType" json:"OperationType,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto1.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Command) GetHead() *Header {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Command) GetOperationType() int64 {
	if m != nil {
		return m.OperationType
	}
	return 0
}

// 操作信息处理结果
type CommandResult struct {
	OK           bool   `protobuf:"varint,1,opt,name=OK" json:"OK,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=ErrorMessage" json:"ErrorMessage,omitempty"`
}

func (m *CommandResult) Reset()                    { *m = CommandResult{} }
func (m *CommandResult) String() string            { return proto1.CompactTextString(m) }
func (*CommandResult) ProtoMessage()               {}
func (*CommandResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CommandResult) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *CommandResult) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

// 客户端列表
type ClientListResut struct {
	Result  *CommandResult `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
	Clients []string       `protobuf:"bytes,2,rep,name=Clients" json:"Clients,omitempty"`
}

func (m *ClientListResut) Reset()                    { *m = ClientListResut{} }
func (m *ClientListResut) String() string            { return proto1.CompactTextString(m) }
func (*ClientListResut) ProtoMessage()               {}
func (*ClientListResut) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ClientListResut) GetResult() *CommandResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ClientListResut) GetClients() []string {
	if m != nil {
		return m.Clients
	}
	return nil
}

// 获取历史信息
type MessageHistories struct {
	Result    *CommandResult `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
	Content   string         `protobuf:"bytes,2,opt,name=Content" json:"Content,omitempty"`
	Publisher string         `protobuf:"bytes,3,opt,name=Publisher" json:"Publisher,omitempty"`
	Time      int64          `protobuf:"varint,4,opt,name=Time" json:"Time,omitempty"`
}

func (m *MessageHistories) Reset()                    { *m = MessageHistories{} }
func (m *MessageHistories) String() string            { return proto1.CompactTextString(m) }
func (*MessageHistories) ProtoMessage()               {}
func (*MessageHistories) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MessageHistories) GetResult() *CommandResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *MessageHistories) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageHistories) GetPublisher() string {
	if m != nil {
		return m.Publisher
	}
	return ""
}

func (m *MessageHistories) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto1.RegisterType((*Header)(nil), "proto.Header")
	proto1.RegisterType((*Content)(nil), "proto.Content")
	proto1.RegisterType((*LoginMessage)(nil), "proto.LoginMessage")
	proto1.RegisterType((*LogoutMessage)(nil), "proto.LogoutMessage")
	proto1.RegisterType((*Command)(nil), "proto.Command")
	proto1.RegisterType((*CommandResult)(nil), "proto.CommandResult")
	proto1.RegisterType((*ClientListResut)(nil), "proto.ClientListResut")
	proto1.RegisterType((*MessageHistories)(nil), "proto.MessageHistories")
}

func init() { proto1.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xe9, 0x76, 0xbb, 0xda, 0xb1, 0xab, 0x12, 0x44, 0xf6, 0xe0, 0xa1, 0x06, 0x0f, 0x1e,
	0xa4, 0x07, 0xf5, 0x0d, 0x8a, 0xd0, 0xd2, 0xd5, 0x4a, 0x50, 0xc1, 0xe3, 0x96, 0x1d, 0xb6, 0x81,
	0x26, 0x29, 0x49, 0x0a, 0xfa, 0x0e, 0x3e, 0xb4, 0xec, 0x24, 0x54, 0x7a, 0x2b, 0xd2, 0xd3, 0x26,
	0x7f, 0x32, 0xdf, 0xff, 0xcf, 0x4e, 0x20, 0x57, 0xe8, 0x5c, 0xd5, 0xe0, 0x68, 0x6d, 0x8d, 0x37,
	0xac, 0x47, 0x1f, 0xfe, 0x08, 0xd9, 0x04, 0xab, 0x1a, 0x2d, 0x63, 0x90, 0xbe, 0x7d, 0xaf, 0xb1,
	0xe8, 0x0c, 0x3b, 0xb7, 0x5d, 0x41, 0x6b, 0x76, 0x09, 0x59, 0x89, 0xba, 0xf1, 0xcb, 0x22, 0x21,
	0x35, 0xee, 0xf8, 0x17, 0x1c, 0x8d, 0x8d, 0xf6, 0xa8, 0x3d, 0xbb, 0x86, 0xb4, 0x05, 0x50, 0xd9,
	0xc9, 0x7d, 0x1e, 0xe8, 0xa3, 0xc0, 0x14, 0x74, 0xc4, 0x8a, 0xed, 0x6d, 0xc2, 0xf4, 0xc5, 0xb6,
	0xf8, 0x0a, 0xfa, 0xaf, 0x9b, 0xc5, 0x4a, 0xba, 0x25, 0xda, 0xa2, 0x4b, 0x67, 0x7f, 0x02, 0x25,
	0x92, 0x0a, 0x8b, 0x34, 0x26, 0x92, 0x0a, 0xf9, 0x3b, 0x0c, 0x4a, 0xd3, 0x48, 0xfd, 0x1c, 0x9a,
	0xd9, 0xc7, 0x9e, 0x41, 0xfa, 0x52, 0x29, 0x8c, 0xde, 0xb4, 0x66, 0xa7, 0x90, 0x4c, 0x6b, 0x72,
	0xec, 0x89, 0x64, 0x5a, 0xf3, 0x0f, 0xc8, 0x4b, 0xd3, 0x98, 0x8d, 0x3f, 0x30, 0x57, 0xb4, 0xad,
	0x2b, 0x55, 0xe9, 0x7a, 0x1f, 0xe2, 0x0d, 0xe4, 0xf3, 0x35, 0xda, 0xca, 0x4b, 0xa3, 0x69, 0x16,
	0xe1, 0xaf, 0xef, 0x8a, 0x7c, 0x0c, 0x79, 0x64, 0x0a, 0x74, 0x9b, 0x95, 0x6f, 0x4d, 0xe7, 0x33,
	0xe2, 0x1e, 0x8b, 0x64, 0x3e, 0x63, 0x1c, 0x06, 0x4f, 0xd6, 0x1a, 0x1b, 0x7b, 0x89, 0x01, 0x77,
	0x34, 0xfe, 0x09, 0x67, 0xe3, 0x95, 0x44, 0xed, 0x4b, 0xe9, 0x7c, 0xcb, 0xf1, 0xec, 0x0e, 0xb2,
	0x00, 0x8c, 0x11, 0x2f, 0x62, 0xc4, 0x1d, 0x33, 0x11, 0xef, 0xd0, 0x50, 0x09, 0xe0, 0x8a, 0x64,
	0xd8, 0xa5, 0xa1, 0x86, 0x2d, 0xff, 0xe9, 0xc0, 0x79, 0xb4, 0x99, 0x48, 0xe7, 0x8d, 0x95, 0xe8,
	0xfe, 0x01, 0x3f, 0xd0, 0x8b, 0x59, 0x64, 0x64, 0xf4, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xda,
	0x66, 0x99, 0xef, 0x00, 0x03, 0x00, 0x00,
}
